schema_version: 1

context:
  name: refnx
  version: "0.1.66"
  sha256: a399cf7d994f89bd65ca675b5e3f9cfb9af5b5d1a193d4b8557db828829309da
  numpy: "2.0.0"
  python_min: "3.11"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/r/refnx/refnx-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  skip: is_abi3 and not python_min
  python:
    version_independent: ${{ is_abi3 }}
  script:
    # rattler-build figures out the {.sh,.bat} extensions
    - build

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: osx
      then: llvm-openmp
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - if: is_abi3
          then: python-abi3
        - cross-python_${{ target_platform }}
        - numpy >=${{ numpy }}
        - cython
        - meson-python
        - ninja
  host:
    - python ${{ python_min }}.*
    - if: is_abi3
      then: python-abi3
    - numpy >=${{ numpy }}
    - cython
    - meson-python
    - ninja
    - pip
    - python-build
    - if: osx
      then: llvm-openmp
  run:
    - python >=${{ python_min }}
    - scipy
    - orsopy
    - if: osx
      then: llvm-openmp

tests:
  - python:
      imports:
        - refnx
      python_version:
        - if: is_abi3
          then: ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pytest
        - if: osx and win
          then: pytest-qt
        - if: is_abi3
          then: abi3audit
        - scipy >=1.2.0
        - matplotlib
        - ipywidgets
        - traitlets
        - corner
        - tqdm
        - attrs
        - qtpy
        - pyside6
        - periodictable
    script:
      - python -c "import refnx;refnx.test(tests=['refnx.reflect.tests.test_reflect'])"
      - if: unix
        then: abi3audit $SP_DIR/refnx/reflect/_creflect.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neutron and X-ray Reflectometry Analysis
  homepage: https://github.com/refnx/refnx
  documentation: https://refnx.github.io

extra:
  recipe-maintainers:
    - andyfaff
